#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run check-format || (
  echo 'oops! your format doesnt looks good. Run npm run format and try commiting again!';
  false;
)

echo 'Ok, the format looks good, how about lint check? 😋'

npm run check-lint || (
  echo 'oops! you did not meet the linting standards!';
  false;
)

echo 'Good,there are no lint issues,let us do a stylelint check';

npm run style-lint || (
  echo 'oops! your code doesnot match the stylelint standards!'
  false;
)

echo 'Awesome, you passed all the checks 😍🎉'