# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Tests CI

# on:
#   pull_request:
#     branches: ['main', 'develop']

# jobs:
#   build:
#     name: Run Coverage Tests
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [16.x]

#     steps:
#       - name: Checkout Branch To Runner
#         uses: actions/checkout@v3
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'yarn'
#       - name: Install Yarn
#         run: yarn install --prefer-offline --immutable
#       - name: Run Coverage Tests
#         run: yarn run test:ci
#       - name: Code Coverage Summary Report
#         uses: irongut/CodeCoverageSummary@v1.3.0
#         with:
#           filename: coverage/cobertura-coverage.xml
#           badge: true
#           format: 'markdown'
#           output: 'both'
#       - name: Add Coverage PR Comment
#         uses: marocchino/sticky-pull-request-comment@v2
#         if: github.event_name == 'pull_request'
#         with:
#           recreate: true
#           path: code-coverage-results.md
#       - name: Write to Job Summary
#         run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

