name: Test with Coverage report
on:
    pull_request:
        branches:
            - develop
            - main

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Branch To Runner
              uses: actions/checkout@v3
            - name: Jest coverage report
              uses: ArtiomTr/jest-coverage-report-action@v2.2.1
              id: coverage
              with:
                  package-manager: yarn
                  test-script: yarn test:ci
                  annotations: all
                  output: comment, report-markdown
                env:
                  GITHUB_STEP_SUMMARY: ${{ steps.coverage.outputs.report }}

            # - name: Write to Job Summary
            #   run: echo "Adding coverage to GITHUB_STEP_SUMMARY"
            #   env:
            #     GITHUB_STEP_SUMMARY: ${{ steps.coverage.outputs.report }}
