name: Coverage report
on:
    pull_request:
        branches:
            - develop
            - main

jobs:
    coverage:
        runs-on: ubuntu-latest
    
        strategy:
            matrix:
              node-version: [16.x]
            
        steps:
            - name: Run Coverage Tests
              uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'yarn'
            - name: Install Yarn
              run: yarn install --prefer-offline --immutable
            - name: Jest Coverage Diff
              uses: anuraag016/Jest-Coverage-Diff@V1.4
              with:
                delta: 1
                fullCoverageDiff: true
                runCommand: "npx jest --coverage --collectCoverage=true --coverageDirectory='./' --coverageReporters='json-summary' --forceExit"