name: Coverage Report CI

on:
  pull_request:
    branches:
      - develop
      - main


jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x]
        platform: [ubuntu-latest]
    name: Run Coverage Tests
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install packages
      run: yarn install --prefer-offline --immutable
    - name: Run Tests
      run: yarn run test:ci
    - name: Test Coverage report
      id: testCoverage
      uses: anuraag016/Jest-Coverage-Diff@V1.4
      with:
        fullCoverageDiff: true
        delta: 0.5