name: Coverage report
on:
    pull_request:
        branches:
            - develop
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Jest Coverage Diff
              uses: anuraag016/Jest-Coverage-Diff@V1.4
                with:
                    delta: 1
                    fullCoverageDiff: true
                    runCommand: "npx jest --coverage --collectCoverage=true --coverageDirectory='./' --coverageReporters='json-summary' --forceExit"